localhost:
  image: postgres
  environment:
    POSTGRES_PASSWORD: sapl
    POSTGRES_USER: sapl
    POSTGRES_DB: sapl
  ports:
    - "5532:5432"
web:
  build: .
  command: /bin/sh -c "/bin/sh busy-wait.sh && python3 manage.py bower install && python3 manage.py migrate && /bin/sh gunicorn_start.sh /sapl"
  volumes:
    - .:/sapl
  ports:
    - "8000:8000"
  links:
    - localhost
